version: "3.8"

name: mongo-es-stack
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks: [data-net]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.14.0}
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "${ES_PORT:-9200}:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      # 개발 편의를 위해 보안 비활성화(프로덕션에서는 반드시 활성화)
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms${ES_JAVA_HEAP:-1g} -Xmx${ES_JAVA_HEAP:-1g}
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65536, hard: 65536 }
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    networks: [data-net]

  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION:-8.14.0}
    container_name: kibana
    restart: unless-stopped
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      # 보안 비활성화한 ES에 연결
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_PUBLICBASEURL=http://localhost:${KIBANA_PORT:-5601}
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5601 >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
    networks: [data-net]

  # (옵션) 간단한 UI가 필요하면 mongo-express 추가 (주석 해제 후 사용)
  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "18081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_AUTH_DATABASE: "admin"
      # Mongo Express 웹 UI 인증 (기본값 admin:pass 대신 사용)
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    depends_on: { mongodb: { condition: service_healthy } }
    networks: [data-net]

volumes:
  mongo-data:
  es-data:

networks:
  data-net:
    driver: bridge
